### ISSUE TITLE
Search field is case sensitive

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#103]
**Build version:**
1.0.99

**Severity:**
Medium;

**Description:**
search field is case sensitive;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Create dishes with name "TEST" and "test" (for example);
2.Open "dish 4" screen;
2.Enter "TEST" (for example) in the search field;

**Actual result:** as a result of the search two dishes with names "TEST" and "test" are displayed;
**Expected result:** as a result of the search one dish with name "TEST" is displayed;

**Workaround:**
No;

**Attachments:**

![3](https://user-images.githubusercontent.com/45947708/52166414-fa657a00-271d-11e9-8872-1c328e1826de.PNG)
![4](https://user-images.githubusercontent.com/45947708/52166415-fa657a00-271d-11e9-83c5-6108aa6ee3c2.PNG)
![5](https://user-images.githubusercontent.com/45947708/52166416-fafe1080-271d-11e9-9d2f-7287fafd8b5a.PNG)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22076989

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/build/artifacts

![default](https://user-images.githubusercontent.com/25455982/52166642-ee2eec00-2720-11e9-8f84-e8085739ad42.png)

**Comment by YuryiDasevich** [comment]
Bug was verified and fixed in the current build.
