### ISSUE TITLE
Wrong navigation to the dish page when using search

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#113]
**Build version:**
1.0.107

**Severity:**
High;

**Description:**
when choosing a dish among the search results you will be redirected to the wrong dish.
The choice of dish is not based on the search results, but on the position of the dish in the general list of dishes;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Create 3 dishes with name "test1", "test2", "test3" and 3 dishes with name "number1","number2","number3" (in that order and names for example);
2.Open dish 4 page;
3.Enter "number" (for example) in the search field;
4.Tap on the dish with name "number2" (for example);

**Actual result:** dish 6 screen of the dish "test2" is displayed;
**Expected result:** dish 6 screen of the dish "number2" is displayed;

**Workaround:**
No;

**Attachments:**

![1](https://user-images.githubusercontent.com/45947708/52534294-d377fb00-2d50-11e9-941a-be127b4f1ef7.png)
![2](https://user-images.githubusercontent.com/45947708/52534292-d377fb00-2d50-11e9-9cfe-68c1ade55ac6.png)
![3](https://user-images.githubusercontent.com/45947708/52534293-d377fb00-2d50-11e9-9831-fcf1bf7a3a0f.png)

**Comment by ordeh** [comment]
Fixed in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22257424

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22257424/artifacts

**Comment by YuryiDasevich** [comment]
Bug was verified and fixed in the current build.
