### ISSUE TITLE
It is impossible to edit description and photo of the existing dish (dish 7 screen)

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#115]
**Build version:**
1.0.107

**Severity:**
Medium;

**Description:**
When editing description or photo of the dish and tapping save button system cannot allow to make changes. Hint "dish with that name already exists" is displayed in the dish name field;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Create dishes with valid name;
2.Open "dish 7" screen of created dish;
3.Add new photo;
4.Edit description with new valid data;
5.Tap "Save" button;

**Actual result:** no changes were applied. Hint "dish with that name already exists" is displayed in dish name field. dish 7 screen is still displaying.;
**Expected result:** editing dish is displayed in list of dishes (dish 4 screen) with new description and photo;

**Workaround:**
You can make changes if rename dish name;

**Attachments:**

![image](https://user-images.githubusercontent.com/45947708/52534519-83e6fe80-2d53-11e9-89c1-fabf7a587567.png)

**Comment by ordeh** [comment]
Fixed in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22257676

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22257676/artifacts

**Comment by YuryiDasevich** [comment]
Bug was verified and fixed in the current build.
