### ISSUE TITLE
Redesign "Share" (Photo from the storage) icon

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#117]
Hello @ordeh ,

Please consider this improvement proposal. Icon for adding dish photo from the gallery has a design that is not appropriate for its purpose (dish 5 screen). And in accordance with UI/UX design it should be replaced.

Here are my variant for it icon: https://icons8.com/icon/86810/photo-gallery

Waiting for your response.

**Comment by ordeh** [comment]
Hi @YuryiDasevich 

Concerning your suggestion, I think that you are right and I' am going to rework this icon.
In near time I' am going to prepare draft design for Dish 5 with new icon and after that we can make a decision concenring new implementation.

BR
Fedor

**Comment by ordeh** [comment]
@YuryiDasevich  what do you think about this?

![default](https://user-images.githubusercontent.com/25455982/52536569-5dce5800-2d6d-11e9-833f-68cb060701f1.png)

**Comment by YuryiDasevich** [comment]
@ordeh it is much better. Thank you for considering my proposal.

Best regards

**Comment by ordeh** [comment]
Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22259693

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22259693/artifacts

**Comment by YuryiDasevich** [comment]
Verified
