### ISSUE TITLE
Possibility to watch photo in full size (dish 6 screen)

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#119]
Hello @ordeh ,

Please consider this improvement proposal. 
In terms of application's specific, it would be better if user will be able to view full size photo of the dish.
I suggest to implement it by clicking on the dish image on the dish 6 screen:

![1](https://user-images.githubusercontent.com/45947708/52537252-93773f00-2d75-11e9-804e-13f7a9fbf627.png)

Waiting for your response.

**Comment by ordeh** [comment]
Hi @YuryiDasevich ,

You are right, this is a good improvement. The current implementation allows you to view the photo in full size only if it exists in a dish. 
I updated requirements for Dish 6

Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22431977

Apk: 
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22431977/artifacts

![default](https://user-images.githubusercontent.com/25455982/52910765-4cc1a180-32ad-11e9-9d0c-d3369cff7f4d.png)

**Comment by YuryiDasevich** [comment]
Hi @ordeh ,
This issue was verified, and it's ok.

But during testing i found this bug - https://github.com/tasks-delivery/craft-dish/issues/130#issue-411210645
