### ISSUE TITLE
Common validation logic

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#126]
Common validation logic for Dish 2 and Dish 7

**Dish Name cannot be empty, warning message 'Dish name cannot be empty or contain only spaces' should be visible**

![default](https://user-images.githubusercontent.com/25455982/52910910-619f3480-32af-11e9-9b78-756366f5e86b.png)

**Comment by ordeh** [comment]
Hi @YuryiDasevich ,

This validation was implemented because it is allowed to keep one style of validation for our application.

Please test this.

Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22432099

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22432099/artifacts

**Comment by YuryiDasevich** [comment]
Hi @ordeh ,
This feature was verified on the screen dish 2 and dish 7.

Build 1.0.137
