### ISSUE TITLE
It is possible to make dish name and description with a newline by using clipboard [dish 6]

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#129]
**Build version:**
1.0.135

**Severity:**
Low;

**Description:**
You can paste a text with many newlines (paragraphs) when creating or editing the dish name/description by using clipboard. And this text will have incorrect view on the dish 6 screen;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Copy text with more than 5 paragraphes 
 _-1
 -2
 -3
 -4
 -5_ 
(for example);
2.Create dish where dish name and dish description will consist of this text;
3.Open dish 6 screen of created dish;

**Actual result:** dish name field takes up too much screen space. Each paragraph of the copied text is displayed on a new line (for dish description and dish name).;
**Expected result:** Each paragraph of the copied text is displayed like a "space" sign (for dish description and dish name);

**Walkaround:**

**Attachments:**

![1](https://user-images.githubusercontent.com/45947708/52915822-83b5a880-32e9-11e9-8873-d43f56b443f8.png)
![2](https://user-images.githubusercontent.com/45947708/52915823-83b5a880-32e9-11e9-9a69-59e8d8a7f3ed.png)
![3](https://user-images.githubusercontent.com/45947708/52915824-83b5a880-32e9-11e9-91a4-380e1889504e.png)

**Comment by ordeh** [comment]
Fixed in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22437007

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22437007/artifacts

![default](https://user-images.githubusercontent.com/25455982/52916663-73a2c680-32f3-11e9-8406-09c62f744fa8.png)

**Comment by YuryiDasevich** [comment]
Bug was verified and fixed in the current build.
