### ISSUE TITLE
"save" button on the dish 7 screen

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#132]
Hi @ordeh ,

Please consider this improvement proposal.
In accordance with UI/UX design this button should be set in the place as the same button on dish 2:

![1](https://user-images.githubusercontent.com/45947708/52917894-655ba700-3301-11e9-971a-97311658a5a4.png)
![2](https://user-images.githubusercontent.com/45947708/52917895-655ba700-3301-11e9-8739-c91d476e7d0e.png)

For that reason, I also propose to perform buttons DELETE and MAKE PHOTO as it done on the dish 1 screen:

![3](https://user-images.githubusercontent.com/45947708/52917896-655ba700-3301-11e9-911e-360544e3b555.png)
![4](https://user-images.githubusercontent.com/45947708/52917897-65f43d80-3301-11e9-9ccb-049f84196219.png)

Waiting for your response.

**Comment by ordeh** [comment]
Hi @YuryiDasevich ,

It makes sense, I'm going to set sprint 0.9.0 for this improvement.

**Comment by ordeh** [comment]
Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23133370

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23133370/artifacts

![изображение](https://user-images.githubusercontent.com/25455982/54488554-0bc0ab00-48b4-11e9-9d69-5b3b44dd1944.png)

**Comment by YuryiDasevich** [comment]
Hi @ordeh  ,
This feature was verified and looks good.
But during the testing i found #147 and #149
