### ISSUE TITLE
Dish name does not fit in the "dish name" field on the screen dish 7 and dish 2

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#149]
**Build version:**
1.0.159

**Severity:**
Low;

**Description:**
Dish name does not fit in the "dish name" field on the screen dish 7 and dish 2 if it filled with a maximum amount of capital letters

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**

1. Open dish 2 screen;
2. Enter a maximum amount of capital letters into "dish name" field;
3. Tap SAVE button;
4.Open dish 7 screen of created dish and check "dish name" field

**Actual result:** the last letter is cut off;
**Expected result:** all letters fit without cutting;

**Walkaround:**

**Attachments:**

![Screenshot_1](https://user-images.githubusercontent.com/45947708/55287773-169c3500-53b6-11e9-93b2-8a8375ecfb1c.png)
![Screenshot_2](https://user-images.githubusercontent.com/45947708/55287774-169c3500-53b6-11e9-80cd-85315364b6df.png)

**Comment by ordeh** [comment]
Cannot reproduce on emulator and real devices. I think that it is not a bug, because we use a standard way for development these fields.

@YuryiDasevich  please close this issue.

![изображение](https://user-images.githubusercontent.com/25455982/55287865-7e06b480-53b7-11e9-9bf9-86952c3b1e86.png)

**Comment by YuryiDasevich** [comment]
@ordeh 
thanks for the explanation!
