### ISSUE TITLE
It's impossible to enter a fractional number as ingredient weight [Ingredient 2]

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#155]
**Build version:**
1.0.183

**Severity:**
Low;

**Description:**
It's impossible to enter a fractional number as ingredient weight cause buttons "." and "," are unclickable;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1. Start creating an ingredient (open ingredient 2 screen)
2. Focus in the ingredient weight field;
3. Tap one number (e.g. 0);
4. Tap "."/"," sign;

**Actual result:** buttons "." and "," are unclickable;
**Expected result:** "."/"," displayed after early entered number in the ingredient weight field;

**Attachments:**

![Screenshot_2](https://user-images.githubusercontent.com/45947708/55683209-f0dad700-5945-11e9-8435-d00c373bc97a.png)

**Comment by ordeh** [comment]
Fixed in build: 
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23658014

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23658014/artifacts

![изображение](https://user-images.githubusercontent.com/25455982/55683481-f2f26500-5948-11e9-9c02-b32608e34835.png)

**Comment by YuryiDasevich** [comment]
Verified and fixed.
