### ISSUE TITLE
Back navigation after adding ingredients [dish 6]

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#156]
Hi @ordeh,

Please consider this improvement proposal.
In accordance with UI/UX design, it's more comfortable for users to return to the dish screen in which the user has added ingredients. 
Now this is implemented inconveniently because the user returns to the home page, from which he will have to return to the list of dishes / particular dish.

Waiting for your response.

**Comment by ordeh** [comment]
Hi @YuryiDasevich ,
Yes, you are right, it is a great idea.
I have been already implemented this, you can check new changes.

Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23664327

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23664327/artifacts

Automation tests passed
![изображение](https://user-images.githubusercontent.com/25455982/55689981-4ccc4c80-5994-11e9-95bc-9360d9a9c4ac.png)

**Comment by xBaNzYx** [comment]
Hi @ordeh 
The navigation in the "adding ingredients" section works according to the new requirement (proposal for improvement).
