### ISSUE TITLE
Different line color under the fields [Ingredient 2]

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#161]
**Build version:**
1.0.232

**Severity:**
Low;

**Description:**
Lines color differs:
-Fields "Ingredient weight" and "Ingredient name" have white line color;
-"Weight unit" has slightly grey color;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1. Start creating an ingredient (open ingredient 2 screen)

**Actual result:** one field is underlined in a different color;
**Expected result:** all fields are underlined in one color;

**Attachments:**

![Screenshot_1](https://user-images.githubusercontent.com/45947708/55685903-e16a8680-5963-11e9-986f-0737616370ad.png)
![Screenshot_2](https://user-images.githubusercontent.com/45947708/55685904-e2031d00-5963-11e9-8af9-ace868017f19.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33491302

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33491302/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh
Application version 1.0.264 was tested.
Environment: Nexus 6P API 27 Android v8.1
[Bug](https://github.com/tasks-delivery/craft-dish/issues/161#issue-430158898) was not detected.
