### ISSUE TITLE
Dish 3 back navigation

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#163]
**Preconditions**: Dish wit name 'test' does not exist in the system.

**Steps**:
1) Open app and click Dishes button
2) Click '+' button
3) Input 'test' in the Dish name field and click Save button
4) Click android-back button

**Actual result**: Dish 1 is shown
**Expected result** Dish 4 is shown

**Requirements**:
https://github.com/tasks-delivery/craft-dish/wiki/Dish-3-(0.0.3)

Hi @YuryiDasevich ,

When I created automation tests for dish 3 screen I faced with navigation issue.
I found you test-case for back navigation and marked it as failed, please after fixing this defect update state of this test-case.

![изображение](https://user-images.githubusercontent.com/25455982/55687686-8e4efe80-5978-11e9-8aa3-a5ec23abb738.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23663983

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23663983/artifacts

Automation tests passed:
![изображение](https://user-images.githubusercontent.com/25455982/55689204-6d8fa480-598a-11e9-89d9-f1c859512677.png)

**Comment by xBaNzYx** [comment]
Hi @ordeh
Application version 1.0.284 was tested.
Environment: Nexus 6P API 27 Android v8.1
[Bug](https://github.com/tasks-delivery/craft-dish/issues/163#issue-430174446) was not detected.
