### ISSUE TITLE
Automated state in test cases

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#167]
Hi @YuryiDasevich 
Please add new column 'Automated' in all test case templates for automation state.
After that I'am going to set states for all test cases.

![изображение](https://user-images.githubusercontent.com/25455982/55689892-13dfa800-5993-11e9-9df9-d36facd340e1.png)

**Comment by xBaNzYx** [comment]
Hi @ordeh 

In next test-cases added new column "Automated":
- Test-cases for sprint 1.3.0
Link: https://docs.google.com/spreadsheets/d/1lZk6q835u6I-ohH8Nt7BR7CFloVeegc3FPBcXObjpQU/edit#gid=570276886
- Test-cases for sprint 1.4.0
Link: https://docs.google.com/spreadsheets/d/1XHyT13Y1lccvWtTqJz9gIGbuO-2eROfzrE7wf57Ae90/edit#gid=2081064899
