### ISSUE TITLE
Regression/Acceptance testing

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#175]
As part of this task, you need to prepare tests for sprint 1.3.0

Please see helpful links below:

Sprint 0.9.0 - https://docs.google.com/spreadsheets/d/1IfS97VHsJ_iCIo5z-9oSr50SGqsO4MNXTRf9xCeWyFo/edit#gid=904047346

Sprint 0.8.0 - https://docs.google.com/spreadsheets/d/1QUq0x-oY74skp1_WLUBDF_Sv1aBxSVJcG8Ulfw3swcE/edit#gid=904047346

Sprint 0.7.0 - https://docs.google.com/spreadsheets/d/1WrWZuMcRUDs6_W4J_05ci3LGsFYa0rr9RWGmURQ6_EY/edit?ouid=103108847269860211388&usp=sheets_home&ths=true

Sprints 0.5.0 - 0.6.0 - https://docs.google.com/spreadsheets/d/1AYN3wEeN_-RGifDuqLMO808yLdl2xjcQ7Mw_iVlm-y0/edit

Sprints 0.4.0 - https://docs.google.com/spreadsheets/d/1hXollp1FwtSA3bBB_erApA_G_W--3mjDjWX80ddj1XQ/edit#gid=904047346

Sprints 0.1.0 - 0.3.0 - https://docs.google.com/spreadsheets/d/1vXRVqGnf7Si2bDT3oMpj6rEMgHbbZMN3YsizWi1iYHs/edit#gid=904047346

**Comment by xBaNzYx** [comment]
Hi @ordeh

Regression/Acceptance testing completed successfully.

**link to test-suite:**
https://docs.google.com/spreadsheets/d/1lZk6q835u6I-ohH8Nt7BR7CFloVeegc3FPBcXObjpQU/edit#gid=2081064899

**Comment by ordeh** [comment]
Hi @xBaNzYx ,

Got it thanks
