### ISSUE TITLE
Update Xamarin version and supported api levels

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#177]
**Acceptance criteria**:

- increase support API level to 29 and android version 10.0.0
- update all visual studio tools
- update build script
- update all NuGet packages

**Comment by ordeh** [comment]
Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33507755

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33507755/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh
The application has been tested on the following platforms:
- Nexus 6P API 29 Android v 10.0
- Nexus 6 API 28 Android v 9.0
- Nexus 6P API 25 Android v 7.1
Critical errors related to application support were not found.
