### ISSUE TITLE
After pressing the android-back button on the "Dish 3" screen, a new dish should not be transferred to the "Dish 4" screen.

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#180]
**Build version:**
1.0.284

**Description:**
After pressing the android-back button on screen “Dish 3”, screen “Dish 4” with the newly created dish is displayed (According to [the requirements for screen “Dish 3”](https://github.com/tasks-delivery/craft-dish/wiki/Dish-3-(0.0.3)), a new dish should not be created);

**Preconditions:** 
Nexus 6P API 27 as test environment;

**Steps:**

   1. Open app and click Dishes button
   2. Click '+' button
   3. Input 'test' in the Dish name field and click Save button
   4. Click android-back button

**Actual result:** «Dish 4» screen appears, new dish added
**Expected result:** «Dish 4» screen appears, no new dish added

**Comment by ordeh** [comment]
Fixed 

![изображение](https://user-images.githubusercontent.com/25455982/84813923-5c740600-b019-11ea-8c92-963fd157a3f0.png)
