### ISSUE TITLE
Unable to install apk file on device with "API 21", Error: INSTALL_FAILED_DEXOPT

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#181]
**Build version:**
1.0.284;

**Environment;**
Nexus 6 API 21 Android v5.0;

**Description:**
Unable to install the application on the device. Error: INSTALL_FAILED_DEXOPT;

**Actual result:** during installation, the device generates an error (see attachment);
**Expected Result:** Application Installed;

**Attachment:**
![изображение](https://user-images.githubusercontent.com/66793481/84817471-aeb72600-b01d-11ea-9623-c997a391893d.png)

**Comment by ordeh** [comment]
Unfortunately, we need to increase minimal support API version to 23. 

requestPermissions method was added in API Level 23 so we can not use it on API < 23.

![изображение](https://user-images.githubusercontent.com/25455982/85327835-4d3cfe80-b4d8-11ea-9ff6-2a39e27d53d0.png)

https://forums.xamarin.com/discussion/95882/java-lang-nosuchmethoderror-no-non-static-method-landroid-widget-compoundbutton-xamarin-android

Api version increased in build:

https://ci.appveyor.com/project/ordeh/craft-dish/builds/33673028

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/33673028/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh 

Build version:
1.0.297;

Environment;
Nexus 6 API 23 Android v6.0;

No bugs were found during application installation.
