### ISSUE TITLE
The application logo does not meet the requirements

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#183]
The application logo does not meet the requirements.
Link to requirements:
https://github.com/tasks-delivery/craft-dish/wiki/Common-requirements

**Comment by ordeh** [comment]
@xBaNzYx 

Could you provide more details?

I mean you need to provide expected result, actual result, preconditions, link to build, and steps.

**Comment by xBaNzYx** [comment]
Hi @ordeh 

**Build version:**
1.0.284 - build, on which a discrepancy was found;
1.0.286 - secondary error checking version;

**Environment;**
Nexus 6P API 27 Android v8.1;

**Preconditions:**
The application is installed on the device;

**Link to requirements:**
https://github.com/tasks-delivery/craft-dish/wiki/Common-requirements;

**Steps:**
1.	Find the icon to launch the application;

**Actual result:** the application launch icon is located in the device’s application menu and has the following logo - a blue image of a knife and spoon on a white square background;
**Expected result:** the application launch icon is on the workspace and has the following logo - a blue image of a knife and spoon on a black square.

**Attachments:**
![Screenshot_1592666949](https://user-images.githubusercontent.com/66793481/85205454-1e7e2700-b324-11ea-952f-c668704f8c2e.png)

**Comment by ordeh** [comment]
@xBaNzYx 

Hi @xBaNzYx 

The background depends on the theme on the device, this is not a bug
