### ISSUE TITLE
The navigation requirements for screen "Ingredient 2" contain an error.

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#184]
The navigation requirements for screen "Ingredient 2" contain an error.
After click "Save-button", the "Ingredient 1" screen should appear with data on the new ingredient.
Link to requirements: https://github.com/tasks-delivery/craft-dish/wiki/Ingredient-2-(0.0.2)

**Comment by ordeh** [comment]
@xBaNzYx 

Could you provide more details?

I mean you need to provide expected result, actual result, preconditions, link to build and steps.

**Comment by xBaNzYx** [comment]
Hi @ordeh

**Build version:**
1.0.286 

**Environment;**
Nexus 6P API 27 Android v8.1;

**Preconditions:**
- The system has created one dish; 
- "Dish 4" screen is displayed;

**Link to requirements:** 
https://github.com/tasks-delivery/craft-dish/wiki/Dish-7-(0.0.7);

**Steps:**
1. Click on a dish from the preconditions; 
2. Tap the "Edit" icon; 
3. Find “Save” button; 

**Actual result:** The Save button is located at the bottom of the screen.;
**Expected result:** The "Save" button is in the middle of the screen, the 3rd in the same row as the "Delete" and "Make photo" buttons.

**Attachments:**

**Comment by ordeh** [comment]
Fixed

![изображение](https://user-images.githubusercontent.com/25455982/85323231-54600e80-b4d0-11ea-9c59-02c887606451.png)

For this moment navigation property depends on a place where was redirect to a screen

Navigation chain **Dish 5 -> ingredient 1 -> ingredient 2** will provide name of the screen from that was a redirection and name of dish

Navigation chain **ingredient 1 -> ingredient 2** will provide name of the screen from that was a redirection 

![изображение](https://user-images.githubusercontent.com/25455982/85323339-7eb1cc00-b4d0-11ea-8dff-e885a6d61d08.png)
