### ISSUE TITLE
The discrepancy of the general style of "Hint"

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#185]
**Summary:**
The system has a different hint display style. In one case, the “Hint” is displayed only in the form of an icon (see screen 1 in the attachment. The error text is displayed after clicking on the icon "Hint"), in the second case, the icon with the accompanying error text (see screen 2 in the attachment). Since the requirements for the Hint display are not formed, it should be guided by the principle of a general display style.

**Build version:**
1.0.286 

**Environment;**
Nexus 6P API 27 Android v8.1;

**Preconditions:**
- The system has created one dish; 
- Screen “Dish 2” is displayed, fields “Dish name” and “Dish description” a blank. “Save” button is showed;

**Steps:**
1.	Tap “Save” button;
2.	Tap “Dish name” field and type name is preconditions;
3.	Tap “Android back” button
4.	Tap “Save” button.

**Actual result:** Different display styles for Hint;
**Expected result:** Hint should be displayed in one style;

**Attachment:**
screen 1
![изображение](https://user-images.githubusercontent.com/66793481/85287557-1d243a00-b49d-11ea-8d51-35f509829d5a.png)
screen 2
![изображение](https://user-images.githubusercontent.com/66793481/85287582-244b4800-b49d-11ea-850a-a91ac1c4739f.png)

**Comment by ordeh** [comment]
Hi @xBaNzYx 

The behavior you described is correct, not a bug

If the focus is on the 'Dish name' field, the hint will automatically open with text of hint, but if there is no focus, it will just be an icon visible without text.

**Comment by xBaNzYx** [comment]
Hi @ordeh 

I double-checked the hint playback.
Reproduction of the hint text occurs according to your explanation.
