### ISSUE TITLE
Incorrect location of the "Save" button on the "Dish 7" screen

### ISSUE THREAD

**Issue by xBaNzYx** [tasks-delivery/craft-dish#186]
**Build version:**
1.0.286

**Environment;**
Nexus 6P API 27 Android v8.1;

**Preconditions:**
- The system has created one dish;
- "Dish 4" screen is displayed;

**Link to requirements:**
https://github.com/tasks-delivery/craft-dish/wiki/Dish-7-(0.0.7);

**Steps:**
1. Click on a dish from the preconditions;
2. Tap the "Edit" icon;
3. Find “Save” button;

**Actual result:** "Save" button is located at the bottom of the screen.;
**Expected result:** "Save" button is in the middle of the screen, the 3rd in the same row as the "Delete" and "Make photo" buttons.

**Attachments:
Actual result:**
![изображение](https://user-images.githubusercontent.com/66793481/85298818-359c5080-b4ad-11ea-9610-8884516a1896.png)
**Expected result:**
![изображение](https://user-images.githubusercontent.com/66793481/85298861-40ef7c00-b4ad-11ea-914b-a798a45d9475.png)

**Comment by ordeh** [comment]
Hi @xBaNzYx 

It was implemented in https://github.com/tasks-delivery/craft-dish/issues/132

I updated image in wiki https://github.com/tasks-delivery/craft-dish/wiki/Dish-7-(0.0.7)
