### ISSUE TITLE
Add database migration

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#21]
As result, we should have 2 databases:
- test DB - for testing
- production DB for release

**Comment by ordeh** [comment]
Hi @YuryiDasevich ,
You can check this issue, all data should be overridden after reinstall apk.

Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23476070

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23476070/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh
Database migration was verified by reinstalling application version 1.0.283. (with filled base: dishes and ingredients), to version 1.0.284. According to the results of reinstallation: no errors were detected, all data created in version 1.0.283 was transferred to the new version of the application (1.0.283).
