### ISSUE TITLE
Add  multi-languages support

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#26]
An application should have 2 languages:
 - Russian
 - English

**Comment by ordeh** [comment]
Implemented in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23136455

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23136455/artifacts

**Comment by xBaNzYx** [comment]
Hi @ordeh
The application has been tested (build version 1.0.284) in two languages:
- Russian
- English
No errors related to localization were found.
