### ISSUE TITLE
Prepare test environment

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#38]
- Install JDK and JRE 1.8++
 - Investigate Android Studio and how to create an emulator
 - Investigate how to install apk files.

**Comment by YuryiDasevich** [comment]
@ordeh hello. Clarify please, how can i specified JDK to run the emulator.
You can see my problem in the attachments.

P.S. 
JDK is already installed on my PC.

![fail 0 1](https://user-images.githubusercontent.com/45947708/50386154-81244180-06f2-11e9-8afa-2e4e63f21bd3.PNG)

**Comment by ordeh** [comment]
Hello @YuryiDasevich ,

You need to check the path to Android SDK in project structure

![default](https://user-images.githubusercontent.com/25455982/50386339-7919d100-06f5-11e9-98f3-de3c8e41d1bd.png)

![default](https://user-images.githubusercontent.com/25455982/50386327-6b644b80-06f5-11e9-91e3-859750fe71bf.png)

Regards Fedor

**Comment by YuryiDasevich** [comment]
Environment preparation was done well.
APK file was installed successfully.
![default](https://user-images.githubusercontent.com/45947708/50735506-365dfb80-11c1-11e9-8848-fc8cdbe0b642.PNG)
