### ISSUE TITLE
Prepare test-tracking system

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#39]

**Comment by YuryiDasevich** [comment]
Hello @ordeh ,

Here is URL on Google doc with preparing structure for test cases - https://docs.google.com/spreadsheets/d/13zYdKADOoegGQ56-xAI6S2t7IO_wIaU-MdykNPGWFsk/edit?usp=sharing

Best regards,
Yuryi.

**Comment by ordeh** [comment]
Good job
