### ISSUE TITLE
Unable to install APK file into emulator

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#47]
**Severity:** Critical;

**Priority:** High;

**Description:** Unable to install apk file into emulator. The installation goes in a circle and nothing happens;
Environment: Nexus 6P API 25, Nexus 6P API 27;
Actual result: APK file is not installed;
Expected result: APK file is installed;

**Steps to reproduce:**
1.Run device (Nexus 6P API 27) at Android Studio;
2.Drag and drop APK into device;
3.Watch on the device's screen;

**Workaround:** No;

**Attachments:**

![111](https://user-images.githubusercontent.com/45947708/50734399-9f3c7800-11af-11e9-83ef-ca8701780a6b.PNG)
![222](https://user-images.githubusercontent.com/45947708/50734396-977cd380-11af-11e9-9b0e-fdc93eadace3.PNG)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21413941

Apk available:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21413941/artifacts

![default](https://user-images.githubusercontent.com/25455982/50734754-f5f88080-11b4-11e9-8896-b6a6a5c432ae.png)

**Comment by ordeh** [comment]
@YuryiDasevich 

After testing, close this task and  in  task 'https://github.com/tasks-delivery/craft-dish/issues/38' provide the results.
