### ISSUE TITLE
Redesign splash screen

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#63]
New design should be implemented

![default](https://user-images.githubusercontent.com/25455982/52537671-5eb9b680-2d7a-11e9-9b64-270e02b69913.png)

**Comment by ordeh** [comment]
Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22260684

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22260684/artifacts

**Comment by YuryiDasevich** [comment]
The feature was verified.
