### ISSUE TITLE
Tab "Dishes" on the screen "dish 1" not clickable on the upper and lower boundary of the button

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#64]
**Severity:** Low;
 
**Description:** Unable to tap on the tab "Dishes" on the upper and lower borders of the button;
Actual result: it is possible to tap on the tab "Dishes" only in center;
Expected result: whole image of the button "Dishes" is clickable;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Open screen "dish 1";
2.Tap on the upper/lower boundary of the "Dishes" tab;

**Walkaround:** No;

**Attachments:** 

![image](https://user-images.githubusercontent.com/45947708/51087108-cf5fba00-175f-11e9-9b3e-9b45df26a39a.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21585100

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21585100/artifacts
