### ISSUE TITLE
The system allows you to create Dish with "Dish name" filled only of "spaces"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#70]
**Build version:**
1.0.56

**Severity:**
Low;

**Description:** The system allows you to create Dish with "Dish name" filled only of "spaces";
Actual result: A dish with the name consisting of spaces was created;
Expected result: It is impossible to create a dish with the name consisting of spaces;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Type any number of space characters (from 1 to 30) into the "Dish name" field;
2.Tap on the button "SAVE";

**Workaround:**
No;

**Attachments:**

![screenshot_1547893702](https://user-images.githubusercontent.com/45947708/51425603-71afef80-1bef-11e9-8106-dd72a0f78ef0.png)
![screenshot_1547894091](https://user-images.githubusercontent.com/45947708/51425604-72e11c80-1bef-11e9-8c41-9ad9419b1a7d.png)

**Comment by ordeh** [comment]
Fixed in build: 
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21751641

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21751641/artifacts

**Comment by YuryiDasevich** [comment]
Bug is verified and fixed in the current build.
