### ISSUE TITLE
Incorrect android-back button navigation on the screen "dish 4" after pressing "skip" on the screen "dish 3"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#78]
**Build version:**
1.0.66

**Severity:**
Low;

**Description:** 
If you tap "skip" button on the "Dish 3" screen , and after loading "Dish 4" screen, you tap "android-back" button it will navigate you back to "Dish 3" screen.

Actual result: "Dish 3" screen appears;
Expected result: "Dish 1" screen appears;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Open "Dish 2" screen;
2.Enter random valid data in the "Dish name" field;
3.Tap "Save" button;
4.Tap "Skip" button;
5.Tap "andoid-back" button;

**Workaround:**
No;

**Attachments:**
No.

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21959901

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21959901/artifacts

**Comment by YuryiDasevich** [comment]
Bug is verified and fixed in the current build.
