### ISSUE TITLE
Permission manager

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#79]
Implement dialogs for permissions to camera and phone storage.

Common requirements:
Checkbox 'Don't ask again' should not be visible for the first appearance of permission dialog

Camera permission
Dialog should be visible by clicking camera icon. (only if camera permission not granted yet)

| Selected Element| Navigate to| Pass data to next screen|
| :-----------| :-------: | :--------|
| Allow - button| Camera | None |
| Deny - button| Dish 5 and permission dialog close  | None |

![default](https://user-images.githubusercontent.com/25455982/51912524-a0934600-23e5-11e9-8f62-c39600331b9e.png)

Storage permission
Dialog should be visible on Splash screen. (only if storage permission not granted yet)

| Selected Element| Navigate to| Pass data to next screen|
| :-----------| :-------: | :--------|
| Allow - button| Splash screen is loaded and after that navigation on Dish 1| None |
| Deny - button| Permission dialog is shown again  | None |

![default](https://user-images.githubusercontent.com/25455982/51912947-886ff680-23e6-11e9-9bed-442e1ccaedd8.png)

Comment: This implementation not exists on design project, because it is standard android permission dialogs.

Requirements:
https://github.com/tasks-delivery/craft-dish/wiki/Permission-manager-(3.0.1)

**Comment by ordeh** [comment]
Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/21969403

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21969403/artifacts

**Comment by YuryiDasevich** [comment]
Feature was tested.

Test-cases link:
[PM test cases](https://docs.google.com/spreadsheets/d/1T-a9QgtCOiEV8TkohjAQ_eddcTAHgkN4Y-rVDkZyAF8/edit?usp=sharing)

Test cases ID:

* S7_1.9 , S7_1.10
* S7_2.1 , S7_2.2
