### ISSUE TITLE
Search field on "dish 4" is not closed and is not cleared after back-navigation from "dish 2"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#82]
**Build version:**
1.0.73

**Severity:**
Low;

**Description:** 
Search field on "dish 4" is **not closed** and is **not cleared** (if you navigate to "dish 2" when cursor was focused in search field) after back-navigation from "dish 2";

Actual result: after back-navigation the search field is in focus and it is filled with entered data;
Expected result: search field is closed and cleared after back-navigation;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Enter any valid data in the search field;
2.Tap floating action button;
3.Wait till navigate to the screen "dish 2" and tap Android-back button/"Back arrow" button;
4.Watch on the screen;

**Workaround:**
No;

**Attachments:**
![1](https://user-images.githubusercontent.com/45947708/51805586-547ac100-2280-11e9-9a49-043a3e5733b5.png)
![2](https://user-images.githubusercontent.com/45947708/51805588-56448480-2280-11e9-9bba-d9fa57da4def.png)
![3](https://user-images.githubusercontent.com/45947708/51805589-59d80b80-2280-11e9-8c92-b92cf4d645fc.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21960107

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21960107/artifacts

**Comment by YuryiDasevich** [comment]
Bug is verified and fixed in the current build.
