### ISSUE TITLE
Auto-focus does not set in the search field and keyboard does not pop-up after tapping "search" button on the screen "dish 4"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#84]
**Build version:**
1.0.73

**Severity:**
Low;

**Description_1:**
Auto-focus does not set in the search field after tapping "search" button on the screen "dish 4"

Actual result: auto-focus is not set in the search field;
Expected result: Auto-focus is set in the search field;

**Description_2:**
Keyboard does not pop-up after tapping "search" button on the screen "dish 4". To open the keyboard you need to tap on the search field (after pressing the search "button")

Actual result: keyboard does not pop-up;
Expected result: keyboard pops-up;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Tap "search" button;
2.Watch on the screen;

**Workaround:**
No;

**Attachments:**

![3](https://user-images.githubusercontent.com/45947708/51806126-0d43fe80-2287-11e9-9bdf-1c00351cf7de.png)
![2](https://user-images.githubusercontent.com/45947708/51806127-0fa65880-2287-11e9-862e-ec71711c4b98.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21960698

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21960698/artifacts

**Comment by YuryiDasevich** [comment]
Bug is verified and fixed in the current build.
