### ISSUE TITLE
Keyboard does not disappear after tapping "close search" button on the screen "dish 4"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#85]
**Build version:**
1.0.73

**Severity:**
Low;

**Description:**
Keyboard does not disappear after tapping "close search" button on the screen "dish 4"

Actual result: keyboard is displaying;
Expected result: keyboard is not displayed;

**Preconditions:**
Nexus 6P API 27 as test environment;

**Steps to reproduce:**
1.Tap "search" button;
2.Tap on the search field;
3.Tap "close search" button;
4.Watch on the screen;

**Workaround:**
No;

**Attachments:**

![1](https://user-images.githubusercontent.com/45947708/51806289-5301c680-2289-11e9-9108-b5ebe4f61857.png)
![2](https://user-images.githubusercontent.com/45947708/51806290-539a5d00-2289-11e9-8d71-3b08b51e1efe.png)

**Comment by ordeh** [comment]
Fixed in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21961145

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21961145/artifacts

**Comment by YuryiDasevich** [comment]
Bug is verified and fixed in the current build.
