### ISSUE TITLE
Number of displaying characters in the description on the screen "dish 4"

### ISSUE THREAD

**Issue by YuryiDasevich** [tasks-delivery/craft-dish#86]
Hello @ordeh ,

Please consider this improvement proposal. The number of characters displayed in the “description” field on the “Dish 4” screen should be reduced, because in terms of convenience, dishes with a large description will take up a lot of space on the screen.

Here are some test screens:

![1](https://user-images.githubusercontent.com/45947708/51806510-99582500-228b-11e9-9981-6d8e31639d0b.png)
![2](https://user-images.githubusercontent.com/45947708/51806511-99582500-228b-11e9-8ec9-3a478eec0155.png)
![3](https://user-images.githubusercontent.com/45947708/51806512-99f0bb80-228b-11e9-9d92-a7b20b7df99a.png)

**Build version:
1.0.73**

Waiting for your response.

**Comment by ordeh** [comment]
Implemented in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/22426520

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/22426520/artifacts

According to this issue the following improvements were implemented:

- Dish name is cut off, if it exceeds one line, the description of a dish is cut off if it is over two lines

![default](https://user-images.githubusercontent.com/25455982/52905547-cffedb00-324c-11e9-8ca5-1f107ca75adc.png)

- Keyboard action button was changed to more friendly and logically, the same for Dish 7

![default](https://user-images.githubusercontent.com/25455982/52905595-8367cf80-324d-11e9-98b5-e5d28bd42824.png)

- Dish 2, Dish 7 forms were reworked

![default](https://user-images.githubusercontent.com/25455982/52905630-df325880-324d-11e9-9042-e581eee89180.png)

**Comment by YuryiDasevich** [comment]
Hi @ordeh ,
This issue was verified, and it's ok.

But during testing i found this bug - https://github.com/tasks-delivery/craft-dish/issues/129#issue-411205375
