### ISSUE TITLE
UI elements are not scaled on Huawei P10 Lite

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#87]
**Preconditions**: Huawei P10 Lite as test environment

**Steps**:
1. Open app and wait for Dish 1 screen to load
2. Click button Dishes and  click floating button
3. Input dish name 'test' and click Save button
4. Click Attach button

**Actual result**: UI elements are not scaled on Huawei P10 Lite
![image](https://user-images.githubusercontent.com/25455982/51846281-5b5e0e00-232a-11e9-9847-f279f5a9b58d.png)

**Expected result**: UI elements are scaled on Huawei P10 Lite

**Build**:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21923708

Comment: On Samsung S8+ works fine

**Comment by ordeh** [comment]
@YuryiDasevich please recheck UI part on emulator.

Fixed in build: https://ci.appveyor.com/project/ordeh/craft-dish/builds/21974311

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21974311/artifacts

![default](https://user-images.githubusercontent.com/25455982/51923468-1d311f00-23fc-11e9-91c5-8e7be86e04e2.png)

**Comment by YuryiDasevich** [comment]
Bug was verified and fixed in the current build.
