### ISSUE TITLE
List of dishes icons are scaled in dish 4 screen

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/craft-dish#89]
Preconditions: Huawei P10 Lite as test environment and dishes exist in the system.

Steps:
1. Open app and wait for Dish 1 screen to load
2. Click button Dishes and click floating button

Actual result: List of dishes icons are scaled in dish 4 screen
![image](https://user-images.githubusercontent.com/25455982/51847665-37e89280-232d-11e9-903e-13c06dd40401.png)

Expected result: List of dishes icons are scaled in dish 4 screen

**Build**:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/21923708

Comment: On Samsung S8+ works fine

**Comment by ordeh** [comment]
Fixed on all real devices and  emulator in build:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23133024

Apk:
https://ci.appveyor.com/project/ordeh/craft-dish/builds/23133024/artifacts

Hi @YuryiDasevich ,
You can note on a picture bellowe that text of dishes stayed in one level on vertical.
However, icon of dish different from 'not found' icon, we cannot fix this because we use the standart way for image loading.  Image size 'not found icon' will different  on ~ 2-5 px;

![изображение](https://user-images.githubusercontent.com/25455982/54487930-c51b8280-48ac-11e9-9dbf-7956a4176afc.png)

![изображение](https://user-images.githubusercontent.com/25455982/54487983-57238b00-48ad-11e9-8e61-d79de2491890.png)

**Comment by YuryiDasevich** [comment]
Hi @ordeh !
I checked it in Build 1.0.159. It was fixed in accordance with your comments.
